### ISSUE TITLE
The APIkey variable is defined in an invalid format

### ISSUE THREAD

**Issue by ivy-rew** [axonivy-market/a-trust-connector#32]
The variables introduced by this connector are invalid, the builds fail with validation errors, when executed with the latest 11.4 releases 
https://github.com/axonivy-market/a-trust-connector/commit/8cafd1b2d0af9a650c968486e6196b45b535ea70

Let's revert this temporary fix and introduce a new better name to maintain this key. At least for the upcoming version, serving LTS 12.

**Comment by nqhoan-axonivy** [comment]
Thank @ivy-rew!
This issue will be resolved after the PR https://github.com/axonivy-market/a-trust-connector/pull/41 was merged to master
